### ISSUE TITLE
Problem with latest MS Teams update

### ISSUE THREAD

**Issue by AndreBrasil** [bananaman2020/teamsvcam#1]
Hi there,

Great work compiling the necessary changes to make virtual webcams work on Microsoft Teams. Unfortunately, the latest update seems to have blocked the script, and when I run the script I get the error: "xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
/Applications/Microsoft Teams.app: the codesign_allocate helper tool cannot be found or used".

I imagine there might be a workaround, so I just wanted to let you know that.

Best,

Andre Brasil

**Comment by 360sym** [comment]
Hey, I forgot to add to the readme. You need to have the command line utilities from Xcode installed this can be done by opening terminal and typing in xcode-select --install

Hope this helps!

**Comment by AndreBrasil** [comment]
Wonderful!

The script worked well on my previous Mac, as I had xcode already installed. With the new Mac I've got, I imagined the latest MS Teams was to blame. With the new code, everything worked!

Thanks!
